name: geocolab
dependencies:
- flask=0.10.1=py27_1
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_0
- markupsafe=0.23=py27_0
- mkl=11.3.1=0
- numpy=1.11.0=py27_0
- openssl=1.0.2h=0
- pip=8.1.1=py27_1
- python=2.7.11=0
- readline=6.2=2
- setuptools=20.7.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- werkzeug=0.11.9=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - pycountry==1.20
  - pystemmer==1.3.0

