name: agu_data
dependencies:
- appnope=0.1.0=py27_0
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- bokeh=0.11.0=py27_1
- configparser=3.5.0b2=py27_1
- cycler=0.9.0=py27_0
- cython=0.23.4=py27_1
- decorator=4.0.9=py27_0
- entrypoints=0.2=py27_1
- flask=0.10.1=py27_1
- freetype=2.5.5=0
- futures=3.0.3=py27_0
- gensim=0.12.2=np110py27_0
- ipykernel=4.3.1=py27_0
- ipython=4.1.2=py27_2
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_0
- jpeg=8d=1
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_2
- jupyter_client=4.2.2=py27_0
- jupyter_console=4.1.1=py27_0
- jupyter_core=4.1.0=py27_0
- lcms=1.19=0
- libpng=1.6.17=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- mistune=0.7.2=py27_1
- mkl=11.3.1=0
- nbconvert=4.2.0=py27_0
- nbformat=4.0.1=py27_0
- nltk=3.1=py27_0
- notebook=4.2.0=py27_0
- numpy=1.10.4=py27_0
- openssl=1.0.2h=0
- pandas=0.17.1=np110py27_0
- path.py=8.2.1=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.5=py27_0
- pil=1.1.7=py27_2
- pip=8.1.1=py27_1
- ptyprocess=0.5=py27_0
- pygments=2.1.3=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- pyzmq=15.2.0=py27_0
- qt=4.8.7=1
- qtconsole=4.2.1=py27_0
- readline=6.2=2
- requests=2.9.1=py27_0
- scikit-learn=0.17=np110py27_1
- scipy=0.17.0=np110py27_0
- seaborn=0.6.0=np110py27_0
- setuptools=20.7.0=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_1
- terminado=0.5=py27_1
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.2.1=py27_0
- werkzeug=0.11.8=py27_0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - agu-data (/Users/thorey/miniconda2/envs/agu_data/lib/python2.7/site-packages/agu_data-1.0-py2.7.egg)==1.0
  - alabaster==0.7.7
  - babel==2.2.0
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup==3.2.1
  - beautifulsoup4==4.4.1
  - docutils==0.12
  - geopy==1.11.0
  - gunicorn==19.4.5
  - ipython-genutils==0.1.0
  - joblib==0.9.4
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - littlehttpserver==0.5.0
  - lockfile==0.12.2
  - matta==1.0.0rc0
  - nose==1.3.7
  - palettable==2.1.1
  - plotly==1.9.5
  - pockets==0.3
  - pycountry==1.19
  - pystemmer==1.3.0
  - regex==2016.1.10
  - selenium==2.48.0
  - skdata==0.0.4
  - snowballstemmer==1.2.1
  - sphinx==1.3.3
  - sphinx-rtd-theme==0.1.9
  - sphinxcontrib-napoleon==0.4.3
  - stop-words==2015.2.23.1
  - tqdm==3.4.0
  - tsne==0.1.5

